# Generated by Django 5.0.1 on 2024-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluser',
            name='info',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='alluser',
            name='meetings',
            field=models.ManyToManyField(null=True, to='meetings.meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='body',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
