# Generated by Django 5.0.1 on 2024-01-24 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_profile_telegram_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(help_text='Введите место проведения мероприятия', max_length=50, verbose_name='Место проведения мероприятия')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Введите название тега', max_length=25, verbose_name='Имя тега')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='event_date',
            field=models.DateTimeField(help_text='Введите дату и время проведения мероприятия', null=True, verbose_name='Дата и время проведения мероприятия'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='max_participant',
            field=models.IntegerField(blank=True, help_text='Введите колличество мест на мероприятии', null=True, verbose_name='Колличество мест на мероприятии'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 1, 24), help_text='Укажите вашу дату рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='body',
            field=models.TextField(blank=True, help_text='Введите информацию о мероприятит', max_length=1000, null=True, verbose_name='Информация о мероприятии'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания мероприятия'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(help_text='Введите название мероприятия', max_length=50, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения мероприятия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, help_text='Введите информацию о вас', max_length=500, null=True, verbose_name='Информация о вас'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='meetings',
            field=models.ManyToManyField(blank=True, help_text='Выберете мероприятия, которые хотите поситить', related_name='profile_list', to='meetings.meeting', verbose_name='Мероприятия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Напишите свой Telegtam', max_length=50, null=True, verbose_name='Telegtam'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='place',
            field=models.ForeignKey(help_text='Изменить место проведения мероприятия', null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.place', verbose_name='Место проведения мероприятия'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите теги для мероприятия', related_name='meetings_list', to='meetings.tags', verbose_name='Теги мероприятия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите интересующие теги', to='meetings.tags', verbose_name='Ваши теги'),
        ),
    ]
