# Generated by Django 5.0.1 on 2024-01-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_place_tags_meeting_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='meetings',
        ),
        migrations.AddField(
            model_name='meeting',
            name='profile_list',
            field=models.ManyToManyField(blank=True, help_text='Выберете мероприятия, которые хотите поситить', related_name='meetings', to='meetings.profile', verbose_name='Мероприятия'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.profile'),
        ),
    ]
