# Generated by Django 5.0.1 on 2024-01-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_remove_profile_meetings_meeting_profile_list_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='profile_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='meetings',
            field=models.ManyToManyField(blank=True, help_text='Выберете мероприятия, которые хотите поситить', related_name='profile_list', to='meetings.meeting', verbose_name='Мероприятия'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
