# Generated by Django 5.0.1 on 2024-02-02 14:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_remove_meeting_max_participant_place_max_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(default='10:00', help_text='Введите время окончания мероприятия', verbose_name='Время окончания мероприятия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default='10:00', help_text='Введите время начала мероприятия', verbose_name='Время начала мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event_date',
            field=models.DateField(default='2024-02-15', help_text='Введите дату проведения мероприятия', verbose_name='Дата проведения мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.ForeignKey(default=1, help_text='Изменить место проведения мероприятия', on_delete=django.db.models.deletion.PROTECT, to='meetings.place', verbose_name='Место проведения мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(2024, 2, 2), help_text='Укажите вашу дату рождения', verbose_name='Дата рождения'),
        ),
    ]
