# Generated by Django 5.0.1 on 2024-02-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_meeting_end_time_meeting_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(help_text='Укажите вашу дату рождения', verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='Введите дату проведения мероприятия', verbose_name='Дата проведения мероприятия')),
                ('start_time', models.TimeField(help_text='Введите время начала мероприятия', verbose_name='Время начала мероприятия')),
                ('end_time', models.TimeField(help_text='Введите время окончания мероприятия', verbose_name='Время окончания мероприятия')),
                ('place', models.ForeignKey(help_text='Выберите место проведения мероприятия', on_delete=django.db.models.deletion.CASCADE, to='meetings.place', verbose_name='Место проведения мероприятия')),
            ],
        ),
    ]
