# Generated by Django 5.0.1 on 2024-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_alter_meeting_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='used',
            field=models.BooleanField(null=True, verbose_name='Использована ли эта запись'),
        ),
    ]
