# Generated by Django 5.0.1 on 2024-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_timetable_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Напишите свой номер телефона', max_length=11, null=True, verbose_name='Ваш номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Выберите интересующие теги', related_name='tags', to='meetings.tags', verbose_name='Ваши теги'),
        ),
    ]
